version: "3"
services:
    app:
        container_name: app-container
        image: app-image
        restart: always
        build: .
        environment:
            - DB_HOST=json-server
        ports:
            - "4001:4001"
    json-server:
        container_name: json-server-container
        image: json-server-image
        build: ./
        ports:
            - "3000:3000"
        command: json-server --watch db.json --host 0.0.0.0